# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ba75da057119ddf39258d8da4336bfdf256e454bad97cd6cc2cde7f439e65bc8bd7e46ac909dc4c07cb10ef7bec656225c625a3f2ac8ad9075a4b30819be5c3

test:
  secret_key_base: 8bc3709da69700855dc08f524996ce8fb2ea41feef161697995a1cdf31d92f85cb66b490bd94d6c3cb3bc95f2de9e5ebe90d5b74dea0d0a692c76b6457669a17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
